# This file created by conda-build 2.1.18
# meta.yaml template originally from:
# C:\projects\flang-feedstock\recipe, last modified Thu Feb 08 20:20:30 2018
# ------------------------------------------------

package:
    name: libflang
    version: 5.0.0
source:
    sha256: 7078a7b24bb2b52789fc5551bd6eeee19082e2923e4d49c2834579e51b43ea74
    url: https://github.com/isuruf/flang/archive/4ddc948697091af68df0a1c63d18e700af047eba.tar.gz
build:
    features:
        - vc14
    msvc_compiler: '14.0'
    noarch: null
    noarch_python: null
    number: '20180208'
    string: vc14_20180208
    track_features:
        - flang
requirements:
    build:
        - clangdev 5.0.0 flang_3
        - bzip2 1.0.6 vc14_1
        - cmake 3.10.0 4
        - curl 7.55.1 vc14_0
        - toolchain 2.1.2 0
        - openssl 1.0.2n vc14_0
        - libxml2 2.9.5 vc14_1
        - flang-meta 0.0.1 0
        - krb5 1.14.2 vc14_0
        - zlib 1.2.11 vc14_0
        - ca-certificates 2017.11.5 0
        - expat 2.2.5 vc14_0
        - vc 14 0
        - libiconv 1.14 vc14_4
        - llvmdev 5.0.0 default_0
        - libssh2 1.8.0 vc14_2
        - tk 8.6.7 vc14_0
        - vs2015_runtime 14.0.25420 0
        - openmp 5.0.0 vc14_0
    run:
        - vc 14
        - openmp ==5.0.0
test:
    files:
        - hello_world.f90
outputs:
    -   name: libflang
        requirements:
            - vc 14
            - openmp ==5.0.0
        script: install_libflang.bat
    -   name: flang
        requirements:
            - clangdev ==5.0.0
            - openmp ==5.0.0
            - vc 14
            - libflang 5.0.0 vc14_20180208
        script: install_flang.bat
about:
    home: http://github.com/flang-compiler/flang
    license: Apache 2.0
    license_file: LICENSE.txt
    summary: Flang is a Fortran compiler targeting LLVM.
extra:
    final: true
    parent_recipe:
        name: flang
        path: C:\projects\flang-feedstock\recipe
        version: 5.0.0
    recipe-maintainers:
        - isuruf
        - xoviat
